# Generated by Django 4.1.13 on 2024-02-29 16:16

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="details",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                default="",
                help_text="Подробное описание выполненной работы",
                verbose_name="Подробное описание",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.CharField(
                help_text="Краткое описание выполненной работы",
                max_length=255,
                verbose_name="Краткое описание",
            ),
        ),
    ]
